<?php

$item = $block->getQuestions();
$answer = $block->getAnswers();

// echo '<pre>'; echo 'hieh';
//     print_r($item->getData());
// echo '</pre>'; 

$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($item)) : ?>
    <div class="block question-list" id="customer-questions">
        <?php if (!$block->getHideTitle()) : ?>
            
        <?php endif ?>
        <div class="block-content">
            <ol class="items question-items">
                <?php foreach ($item as $question) : ?>
                    <li class="item question-item" itemscope itemprop="question" itemtype="">
                        <div class="question-details">
                            <p class="question-author">
                                <span class="question-details-label"><?= $block->escapeHtml(__('Questioned by: ')) ?></span>
                                <strong class="question-details-value" itemprop="author"><?= $block->escapeHtml($question->getName()) ?></strong>
                            </p>
                            <p class="question-date">
                                <span class="question-details-label"><?= $block->escapeHtml(__('Posted on: ')) ?></span>
                                <time class="question-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($question->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($question->getCreatedAt(), $format)) ?></time>
                            </p>
                        </div>
                        <div class="question-title" itemprop="name"><h3><?= $block->escapeHtml('Question: ' . $question->getQuestion()) ?></h3></div>
                        <div class="question-content" itemprop="description">
                            <?= /* @noEscape */ nl2br($block->escapeHtml('The answer of Admin: ' . $question->getAnswer())) ?>
                        </div> 

                        <? foreach($answer->getData() as $temp) : ?>
                            <?php if ($temp['question_id']==$question->getQuestionId()) : ?>
                                <div class="question-content" itemprop="description">
                                    <?= /* @noEscape */ nl2br($block->escapeHtml('Answer of ' .$temp['user_name'] .': ' . $temp['answer_customer'])) ?>
                                </div> 
                            <?php endif ?>
                        <?php endforeach; ?>

                        <?php if ($question->getAnswerStatus()==1) : ?>
                            <form name="saveAnswer" method="post" id="saveAnswer">
                                <div class="question-content" itemprop="description">
                                    <h4>Do you want to answer this question?</h4>
                                    <?= /* @noEscape */ nl2br($block->escapeHtml('Your Answer: ')) ?>
                                    <input style="max-width: 200px" placeholder="Your Answer..." name="answer" type="text"> <br>

                                    <?= /* @noEscape */ nl2br($block->escapeHtml('Your Name:  ')) ?>
                                    <input style="max-width: 209px" placeholder="Your Name Want To Show..." name="user_name" type="text">

                                    <input hidden type="text" name="question_id" value="<?= $question->getQuestionId()?>" />
                                    <!-- <input hidden type="text" name="user_name" value="" /> --> <br>
                                    <button name="submit" type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Answer')) ?></span></button>
                                </div> 
                            </form>
                        <?php endif ?>
                   
                        <hr>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?php if ($item->getSize() > 10) : ?>
                <div class="toolbar question-toolbar">
                    <?= $block->getChildHtml('toolbar') ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>


<script>
require(['jquery'],function(){
    jQuery(document).ready(function() {
        jQuery(".0").hide();
        jQuery("#saveAnswer").submit(function(){
            
            var oneValue = jQuery("input[name='answer']").val();
            var twoValue = jQuery("input[name='user_name']").val();
            var threeValue = jQuery("input[name='question_id']").val();

            var url = "<?php echo $block->getBaseUrl() . 'question/product/answerquestion' ?>";
            console.log(url);
            jQuery.ajax({
            url: url,
            type: "POST",
            data: {answer:oneValue, user_name:twoValue, question_id:threeValue},
            showLoader: true,
            cache: false
        });
        return false;
        });
    });
});
</script>