<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \AHT\Question\Block\Form $block */
?>
<h1><?= $block->getCurrentProduct()->getName() ?></h1>
<div class="block review-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
<div class="block-content">
<form action="<?= $block->escapeUrl('question/product/save') ?>" class="qa-form" method="post" id="qa-form" data-role="product-qa-form" data-bind="scope: 'qa-form'" data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml('form_fields_before') ?>
    <fieldset class="fieldset question-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field field-question required">
            <label for="question_field" class="label"><span><?= $block->escapeHtml(__('Your Name')) ?></span></label>
            <input name="name" data-validate="{required:true}" data-bind="value: qa().detail" type="text">           
            <label for="question_field" class="label"><span><?= $block->escapeHtml(__('Your Email')) ?></span></label>
            <input name="email" data-validate="{required:true}" data-bind="value: qa().detail" type="text">
            <label for="question_field" class="label"><span><?= $block->escapeHtml(__('Your Question')) ?></span></label>
            <div class="control">
                <textarea name="question" id="question_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: qa().detail"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button name="createbtn" type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
        </div>
    </div>
</form>

</div>
</div>
