<?php

$_items = $block->getQuestions();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)) : ?>
    <div class="block question-list" id="customer-questions">
        <?php if (!$block->getHideTitle()) : ?>
            
        <?php endif ?>
        <div class="block-content">
            <ol class="items question-items">
                <?php foreach ($_items as $_question) : ?>
                    <li class="item question-item" itemscope itemprop="question" itemtype="">
                        <div class="question-details">
                            <p class="question-author">
                                <span class="question-details-label"><?= $block->escapeHtml(__('Questioned by: ')) ?></span>
                                <strong class="question-details-value" itemprop="author"><?= $block->escapeHtml($_question->getName()) ?></strong>
                            </p>
                            <p class="question-date">
                                <span class="question-details-label"><?= $block->escapeHtml(__('Posted on: ')) ?></span>
                                <time class="question-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($_question->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($_question->getCreatedAt(), $format)) ?></time>
                            </p>
                        </div>
                        <div class="question-title" itemprop="name"><?= $block->escapeHtml('Question: ' . $_question->getQuestion()) ?></div>
                        <div class="question-content" itemprop="description">
                            <?= /* @noEscape */ nl2br($block->escapeHtml('Answer: ' . $_question->getAnswer())) ?>
                        </div> <hr>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?php if ($_items->getSize() > 10) : ?>
                <div class="toolbar question-toolbar">
                    <?= $block->getChildHtml('toolbar') ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>