<h5>You're asking about:</h5><h3><?= $block->getCurrentProduct()->getName() ?></h3>
<div class="block review-add">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Write Your Own Review')) ?></strong></div>
<div class="block-content">


<?php if ($block->getCustomerSession()->isLoggedIn()) : ?>
<form action="<?= $block->escapeUrl('question/product/savequestion') ?>" class="qa-form" method="post" id="qa-form" data-role="product-qa-form" data-bind="scope: 'qa-form'" data-mage-init='{"validation":{}}'>
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml('form_fields_before') ?>
    <fieldset class="fieldset question-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field field-question required">
            <label for="" class="label"><span><?= $block->escapeHtml(__('Your Name')) ?></span></label>
            <input name="name" data-validate="{required:true}" data-bind="value: qa().detail" type="text">           
            <label for="" class="label"><span><?= $block->escapeHtml(__('Your Email')) ?></span></label>
            <input name="email" data-validate="{required:true}" data-bind="value: qa().detail" type="text">
            <label for="" class="label"><span><?= $block->escapeHtml(__('Your Question')) ?></span></label>
            <div class="control">
                <textarea name="question" id="" cols="5" rows="3" data-validate="{required:true}" data-bind="value: qa().detail"></textarea>
            </div>
            <input hidden type="text" name="productid" value="<?= $block->getCurrentProduct()->getId()?>" />
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button name="submit" type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
        </div>
    </div>
</form>
<?php else : ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= $block->escapeHtml(__('Only registered users can write questions. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>
