<?php
    $token = "9iecwn9qk1vh0io1i5rq9y87icmx045d";
    $url = 'http://localhost/module-aht/rest/default/V1/getList/';
    $ch = curl_init($url);

    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    curl_setopt($ch, CURLOPT_HTTPHEADER, ["Content-Type: application/json", "Authorization: Bearer " . json_decode($token)]);

    $result = curl_exec($ch);

    $result = json_decode($result);

    $tests =[];
    foreach ($block->getQuestions() as $question) {
        $temp = $question->getUserId();
    }

    foreach ($result as $test) {
        if ($temp==$test->user_id) {
            array_push($tests, $test);
        }
    }
?>

<?php if (count($result)) : ?>
    <div class="table-wrapper questions">
        <table class="data table table-questions" id="my-questions-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Product questions')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Created')) ?></th>
                    <th scope="col" class="col item"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col question"><?= $block->escapeHtml(__('Question')) ?></th>
                    <th scope="col" class="col answer"><?= $block->escapeHtml(__('Answer of Admin')) ?></th>
                   
                </tr>
            </thead>
            <tbody>
                <?php foreach ($tests as $question) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Created')) ?>" class="col date"><?= $block->escapeHtml($block->dateFormat($question->created_at)) ?></td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col name">
                        <strong class="product-name">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($block->getProductById($question->product_id))) ?>"><?= $block->getProductById($question->product_id)->getName() ?></a>
                        </strong>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Question')) ?>" class="col question">
                        <?= $block->escapeHtml($question->question) ?>
                    </td>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Answer of Admin')) ?>" class="col answer">
                        <?= $block->escapeHtml($question->answer) ?>
                    </td>
                   
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getToolbarHtml()) : ?>
        <div class="toolbar products-questions-toolbar bottom">
            <?= $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have submitted no questions.')) ?></span></div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
